[config]
name = "Default render graph"
nbPasses = 2

[g-buffer]
order = 0                       # place on the render graph
shader = "gbuffer"              # shader to use
deps = []                       # textures from rendergraph to bind
multiple = false                # presence of multiple identical node
                                # if true, renderer will iterate on every pointOfView
outputs = ["position", "normal", "albedo", "specular"] # output textures
needTextures = true              # textures from material to bind
needLights = false               # light resources to bind
pointOfView = "main_camera"     # which camera should be used?
layers = ["A", "B"]             # layer to be drawn

[final]
order = 1
shader = "blit"
deps = ["position", "normal", "albedo", "specular"]
multiple = false
outputs = ["color"]
needTextures = true
needLights = true
pointOfView = "none"
layers = ["C"]