[config]
name = "Default render graph"
nbPasses = 3

[reflection]
order = 0
shader = "reflection"
deps = []
multiple = true
outputs = ["reflection"]
needTexture = true
pointOfView = "light"

[g-buffer]
order = 1                       # place on the render graph
shader = "gbuffer"              # shader to use
deps = ["reflection"]           # textures from rendergraph to bind
multiple = false                # presence of multiple identical node
                                # if true, renderer will iterate on every pointOfView
outputs = ["position", "normal", "albedo", "specular"] # output textures
needTexture = true              # textures from material to bind
pointOfView = "main_camera"     # which camera should be used?

[final]
order = 2
shader = "blit"
deps = ["position", "normal", "albedo", "specular"]
multiple = false
outputs = []
needTexture = true
pointOfView = "none"