[config]
name = "Forward render graph"
nbPasses = 1

[final]
order = 0                       # place on the render graph
shader = "basic"                # shader to use
deps = []                       # textures from rendergraph to bind
multiple = false                # presence of multiple identical nodes
                                # if true, renderer will iterate on multiple
                                # point of views
outputs = ["color"]             # output textures
needTextures = true             # textures from material to bind
needLights = true               # light resources to bind
pointOfView = "main_camera"     # which camera should be used?
layers = ["A", "B"]             # layer to be drawn