[config]
name = "Forward render graph"
nbPasses = 2

[directional-light]
order = 0
shader = "directional-light"
deps = []
multiple = false
outputs = ["depth_DEPTH"]
precisions = ["low"]
dimensions = "1024x1024"
needTextures = false
needLights = true
pointOfView = "none"
layers = ["A", "B"]

[final]
order = 1                       # place on the render graph
shader = "basic"                # shader to use
deps = ["depth_DEPTH"]          # textures from rendergraph to bind
multiple = false                # presence of multiple identical nodes
# if true, renderer will iterate on multiple
# point of views
outputs = ["color-forward"]     # output textures
precisions = ["low"]            # level of precision for each texture
dimensions = "device"           # dimension for each texture "WIDTHxHEIGHT" or "device"
needTextures = true             # textures from material to bind
needLights = true               # light resources to bind
pointOfView = "main_camera"     # which camera should be used?
layers = ["A", "B"]             # layer to be drawn